const Planets = {
    Sun: {
        size: 13910,
        distance: 0,
        mesh: null,
        path: { mesh: null, gmtry: null, curve: null },
        rotation: 0,
        orbitalVel: 0,
    },
    Mercury: {
        size: 4879,
        distance: 57900000,
        mesh: null,
        path: { mesh: null, gmtry: null, curve: null },
        rotation: 1407.6,
        orbitalVel: 47.9,
    },
    Venus: {
        size: 12104,
        distance: 108200000,
        mesh: null,
        path: { mesh: null, gmtry: null, curve: null },
        rotation: -5832.5,
        orbitalVel: 35,
    },
    Earth: {
        size: 12742,
        distance: 149600000,
        mesh: null,
        path: { mesh: null, gmtry: null, curve: null },
        rotation: 23.9,
        orbitalVel: 29.78,
    },
    Mars: {
        size: 6779,
        distance: 227940000,
        mesh: null,
        path: { mesh: null, gmtry: null, curve: null },
        rotation: 24.6,
        orbitalVel: 24.07,
    },
    Jupiter: {
        size: 139820,
        distance: 778330000,
        mesh: null,
        path: { mesh: null, gmtry: null, curve: null },
        rotation: 9.925,
        orbitalVel: 13.07,
    },
    Saturn: {
        size: 116460,
        distance: 1429400000,
        mesh: null,
        path: { mesh: null, gmtry: null, curve: null },
        rotation: 10.656,
        orbitalVel: 9.69,
    },
    Uranus: {
        size: 50724,
        distance: 2870990000,
        mesh: null,
        path: { mesh: null, gmtry: null, curve: null },
        rotation: -17.24,
        orbitalVel: 6.8,
    },
    Neptune: {
        size: 49244,
        distance: 4495100000,
        mesh: null,
        path: { mesh: null, gmtry: null, curve: null },
        rotation: 16.11,
        orbitalVel: 5.43,
    },
};

 export default Planets;
